- name: governor.http.port
  recommendExpression: 21000
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: atlas.graph.storage.hbase.table
  recommendExpression: governor
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: atlas.graph.index.search.max-result-set-size
  recommendExpression: 10000
  defaultValue: null
  valueType: INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: atlas.graph.index.search.index-name
  recommendExpression: governor
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: atlas.kafka.hook.group.id
  recommendExpression: governor
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionUserName
  recommendExpression: governoruser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionPassword
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: governor.container.limits.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [GOVERNOR_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: governor.container.limits.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [GOVERNOR_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: governor.container.requests.memory
  recommendExpression: -1
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [GOVERNOR_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: governor.container.requests.cpu
  recommendExpression: -1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [GOVERNOR_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: governor.memory.ratio
  recommendExpression: -1
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [GOVERNOR_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE
