---
# apacheds
- name: guardian.apacheds.data.dir
  recommendExpression: "/${service.sid}/data/"
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_APACHEDS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: guardian.apacheds.ldap.port
  recommendExpression: 10389
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_APACHEDS]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: guardian.apacheds.kdc.port
  recommendExpression: 6088
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_APACHEDS]
  onDeps: []
  groups: []
  visibility: READ_WRITE
# guardian-server
- name: guardian.server.port
  recommendExpression: 8380
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: guardian.server.tls.enabled
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<RoleTypes>
    roleTypes: [GUARDIAN_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: guardian.admin.username
  recommendExpression: admin
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: WRITE_ONLY

- name: guardian.admin.password
  recommendExpression: 123
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: WRITE_ONLY #TODO PASSWORD

- name: guardian.ds.root.password
  recommendExpression: Transwarp!
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: WRITE_ONLY

- name: guardian.ds.domain
  recommendExpression: dc=tdh
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: guardian.ds.realm
  recommendExpression: TDH
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: guardian.ds.ldap.tls.enabled
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: guardian.server.kerberos.password
  recommendExpression: <@randomstring len=20/>
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: WRITE_ONLY

- name: guardian.cache.repli.bind.port
  recommendExpression: 7800
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: guardian.client.cache.enabled
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE