- name: sqoop.http.port
  recommendExpression: 12000
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: sqoop.admin.port
  recommendExpression: 12001
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

#- name: sqoop.server.memory
#  recommendExpression: 1024
#  defaultValue: null
#  valueType: MB
#  scope: !<ServiceLevel> {}
#  onDeps: []
#  groups: []
#  visibility: READ_WRITE

- name: sqoop.container.limits.memory
  recommendExpression: 4
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [SQOOP]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: sqoop.container.limits.cpu
  recommendExpression: 1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [SQOOP]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: sqoop.container.requests.memory
  recommendExpression: 0
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [SQOOP]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: sqoop.container.requests.cpu
  recommendExpression: 0
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [SQOOP]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: sqoop.memory.ratio
  recommendExpression: 0.9
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [SQOOP]
  onDeps: []
  groups: []
  visibility: READ_WRITE
